import { useState } from 'react';
import { motion } from 'framer-motion';
import './Features.css';

export default function Features() {
  const [activeTab, setActiveTab] = useState(0);

  return (
    <section id="features" className="features">
      <div className="container">
        <motion.div
          className="features__header"
          initial={{ opacity: 0, y: 30 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true, margin: '-80px' }}
          transition={{ duration: 0.65 }}
        >
          <span className="section-label">Capabilities</span>
          <h2 className="features__title">
            Everything you need to<br />understand any codebase.
          </h2>
          <p className="features__subtitle">
            Built from the ground up for complex legacy systems, multi-repo architectures,
            and continuous code intelligence.
          </p>
        </motion.div>

        {/* Asymmetrical Bento Grid Matrix bounded by exact 2px black lines */}
        <div className="features__bento">
          {/* Card 1: Hero Large Feature - Interactive Knowledge Graph */}
          <motion.div
            className="bento-card bento-card--large"
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true, margin: '-60px' }}
            transition={{ duration: 0.5 }}
          >
            <div className="bento-card__content">
              <div className="bento-card__badge-row">
                <span className="bento-badge">FEATURE 01</span>
                <span className="bento-tag">KNOWLEDGE MAPPING</span>
              </div>
              <h3 className="bento-card__title">Interactive Knowledge Graph</h3>
              <p className="bento-card__desc">
                Explore your entire codebase visually. Every class, method, API endpoint, and database schema
                appears as an interconnected node — tracing deep cross-module call paths instantly.
              </p>
              <div className="bento-card__chips">
                <span className="bento-chip">✓ Dependency Tracing</span>
                <span className="bento-chip">✓ Recursive Call Paths</span>
                <span className="bento-chip">✓ Cross-Repo Links</span>
              </div>
            </div>

            <div className="bento-card__visual bento-card__visual--graph">
              <div className="schematic-header">
                <span className="schematic-title">GRAPH TELEMETRY // AST ENGINE</span>
                <span className="schematic-status">LIVE TRACE</span>
              </div>
              <GraphVisual />
            </div>
          </motion.div>

          {/* Card 2: AI Documentation Generator */}
          <motion.div
            className="bento-card bento-card--medium"
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true, margin: '-60px' }}
            transition={{ duration: 0.5, delay: 0.1 }}
          >
            <div className="bento-card__badge-row">
              <span className="bento-badge">FEATURE 02</span>
              <span className="bento-tag">AI DOCUMENTATION</span>
            </div>
            <h3 className="bento-card__title">Docs That Write Themselves</h3>
            <p className="bento-card__desc">
              Synapse parses logic like a senior engineer — generating production READMEs, API specs, and logic digests.
            </p>

            <div className="bento-card__visual bento-card__visual--code">
              <div className="code-tabs">
                <button
                  className={`code-tab ${activeTab === 0 ? 'active' : ''}`}
                  onClick={() => setActiveTab(0)}
                >
                  README.md
                </button>
                <button
                  className={`code-tab ${activeTab === 1 ? 'active' : ''}`}
                  onClick={() => setActiveTab(1)}
                >
                  openapi.json
                </button>
              </div>
              <div className="code-content">
                {activeTab === 0 ? (
                  <pre className="code-block">
                    <code>
                      <span className="code-h1"># System Architecture</span>{'\n'}
                      <span className="code-comment">&gt; Auto-generated by Synapse AI</span>{'\n\n'}
                      <span className="code-h2">## Core Services</span>{'\n'}
                      - <span className="code-kw">AuthManager</span>: Handles JWT & OAuth2{'\n'}
                      - <span className="code-kw">GraphParser</span>: AST processing pipeline
                    </code>
                  </pre>
                ) : (
                  <pre className="code-block">
                    <code>
                      {'{'}{'\n'}
                      {'  '}<span className="code-kw">"openapi"</span>: <span className="code-str">"3.0.0"</span>,{'\n'}
                      {'  '}<span className="code-kw">"info"</span>: {'{'}{'\n'}
                      {'    '}<span className="code-kw">"title"</span>: <span className="code-str">"Synapse Engine API"</span>{'\n'}
                      {'  '}{'}'}{'\n'}
                      {'}'}
                    </code>
                  </pre>
                )}
              </div>
            </div>
          </motion.div>

          {/* Card 3: Impact Analysis */}
          <motion.div
            className="bento-card bento-card--medium"
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true, margin: '-60px' }}
            transition={{ duration: 0.5, delay: 0.2 }}
          >
            <div className="bento-card__badge-row">
              <span className="bento-badge">FEATURE 03</span>
              <span className="bento-tag">IMPACT ANALYSIS</span>
            </div>
            <h3 className="bento-card__title">Know What Breaks First</h3>
            <p className="bento-card__desc">
              Trace dependency blast radiuses before modifying code. Prevent breaking changes across microservices.
            </p>

            <div className="bento-card__visual bento-card__visual--impact">
              <div className="impact-meter-bar">
                <span className="impact-label">BLAST RADIUS</span>
                <span className="impact-value">LOW RISK (3 MODULES)</span>
              </div>
              <ImpactVisual />
            </div>
          </motion.div>

          {/* Card 4: Legacy Intelligence - Full Width Bar */}
          <motion.div
            className="bento-card bento-card--wide"
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true, margin: '-60px' }}
            transition={{ duration: 0.5, delay: 0.3 }}
          >
            <div className="bento-card__content">
              <div className="bento-card__badge-row">
                <span className="bento-badge">FEATURE 04</span>
                <span className="bento-tag">LEGACY INTELLIGENCE</span>
              </div>
              <h3 className="bento-card__title">Built for Undocumented Codebases</h3>
              <p className="bento-card__desc">
                Designed specifically for code nobody wants to touch. Extract structure from 10-year-old Java, C++, or Python scripts.
              </p>
            </div>

            <div className="bento-card__visual bento-card__visual--legacy">
              <div className="legacy-stats">
                <div className="legacy-stat">
                  <span className="legacy-stat__val">100%</span>
                  <span className="legacy-stat__lbl">AST COVERAGE</span>
                </div>
                <div className="legacy-stat">
                  <span className="legacy-stat__val">14</span>
                  <span className="legacy-stat__lbl">DEAD EXPORTS DETECTED</span>
                </div>
                <div className="legacy-stat">
                  <span className="legacy-stat__val">0</span>
                  <span className="legacy-stat__lbl">CONFIG REQUIRED</span>
                </div>
              </div>
            </div>
          </motion.div>
        </div>
      </div>
    </section>
  );
}

function GraphVisual() {
  return (
    <svg viewBox="0 0 400 200" fill="none" className="bento-svg">
      <pattern id="dot-grid" width="20" height="20" patternUnits="userSpaceOnUse">
        <circle cx="2" cy="2" r="1" fill="#000000" fillOpacity="0.15" />
      </pattern>
      <rect width="400" height="200" fill="url(#dot-grid)" />

      <line x1="200" y1="100" x2="100" y2="50"  stroke="var(--accent-blue)" strokeWidth="2" />
      <line x1="200" y1="100" x2="300" y2="50"  stroke="var(--accent-blue)" strokeWidth="2" />
      <line x1="200" y1="100" x2="110" y2="150" stroke="#000000" strokeWidth="1.8" strokeDasharray="4 4" />
      <line x1="200" y1="100" x2="290" y2="150" stroke="#000000" strokeWidth="1.8" strokeDasharray="4 4" />

      <circle cx="200" cy="100" r="22" fill="var(--bg-surface)" stroke="#000000" strokeWidth="2.5" />
      <circle cx="200" cy="100" r="12" fill="var(--accent-blue)" />

      <circle cx="100" cy="50" r="14" fill="var(--bg-surface)" stroke="#000000" strokeWidth="2" />
      <circle cx="100" cy="50" r="6" fill="var(--accent-blue)" />

      <circle cx="300" cy="50" r="14" fill="var(--bg-surface)" stroke="#000000" strokeWidth="2" />
      <circle cx="300" cy="50" r="6" fill="var(--accent-blue)" />

      <circle cx="110" cy="150" r="11" fill="var(--bg-surface)" stroke="#000000" strokeWidth="1.8" />
      <circle cx="290" cy="150" r="11" fill="var(--bg-surface)" stroke="#000000" strokeWidth="1.8" />

      <rect x="165" y="130" width="70" height="22" rx="4" fill="#000000" />
      <text x="200" y="145" textAnchor="middle" fontSize="9" fill="#FFFFFF" fontWeight="700" fontFamily="sans-serif">APP_CORE</text>

      <rect x="75" y="18" width="50" height="18" rx="3" fill="rgba(0,0,0,0.08)" stroke="#000000" strokeWidth="1" />
      <text x="100" y="30" textAnchor="middle" fontSize="8" fill="#000000" fontWeight="700" fontFamily="sans-serif">AUTH</text>

      <rect x="275" y="18" width="50" height="18" rx="3" fill="rgba(0,0,0,0.08)" stroke="#000000" strokeWidth="1" />
      <text x="300" y="30" textAnchor="middle" fontSize="8" fill="#000000" fontWeight="700" fontFamily="sans-serif">API</text>
    </svg>
  );
}

function ImpactVisual() {
  return (
    <svg viewBox="0 0 320 120" fill="none" className="bento-svg">
      <circle cx="160" cy="45" r="18" fill="var(--bg-surface)" stroke="var(--accent-blue)" strokeWidth="2.5" />
      <circle cx="80"  cy="95" r="11" fill="var(--bg-surface)" stroke="#000000" strokeWidth="1.8" />
      <circle cx="160" cy="95" r="11" fill="var(--bg-surface)" stroke="#000000" strokeWidth="1.8" />
      <circle cx="240" cy="95" r="11" fill="var(--bg-surface)" stroke="#000000" strokeWidth="1.8" />

      <line x1="160" y1="63" x2="80"  y2="84" stroke="var(--accent-blue)" strokeWidth="2" />
      <line x1="160" y1="63" x2="160" y2="84" stroke="var(--accent-blue)" strokeWidth="2" />
      <line x1="160" y1="63" x2="240" y2="84" stroke="var(--accent-blue)" strokeWidth="2" />

      <circle cx="160" cy="45" r="28" stroke="#000000" strokeWidth="1.2" strokeDasharray="3 3" />
    </svg>
  );
}
